### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by JulianWogersien** [wohaopa/ReplayModFixMod#1]
The instructions are wrong i dont see ReplayModTweaker.class anywhere in the downloads or in the jar you can download

**Comment by wohaopa** [comment]
To use replaymod in 2.3.3, you need to delete the org directory in replaymod and replace the ReplayModTweaker.class file. The new ReplayModTweaker.class file is in the replace directory of this repository. You need to install both replaymod and this mod.

**Comment by JulianWogersien** [comment]
thank you this worked
