### ISSUE TITLE
this does not work

### ISSUE THREAD

**Issue by JulianWogersien** [wohaopa/ReplayModFixMod#2]
after i managed to install it (finally)
the game crashed again with an array index out of bounds exception
i am on gtnh 2.3.3 java 8 and using multimc as my launcher
i use linux with kernel version 6.2.0-rt3 64bit

[fml-client-latest.log](https://github.com/wohaopa/ReplayModFixMod/files/12206112/fml-client-latest.log)

**Comment by wohaopa** [comment]
2.3.3 gtnh needs to delete the org folder in replaymod.jar.  will update this mod later. I don't have time to do it now.

**Comment by wohaopa** [comment]
Moreover, you will not be able to see yourself in replay. I haven't found the reason for this bug now. I will try to fix it in a later version.

**Comment by JulianWogersien** [comment]
thank you this worked.
i hope some of the issues will be fixed in the future but its already pretty good that we can use replay mod at all
