### ISSUE TITLE
Deleting `org` not necessary anymore in GNTH 2.5.1

### ISSUE THREAD

**Issue by nueadkie** [wohaopa/ReplayModFixMod#3]
Previously, Minecraft would crash on load because of the Spongepowered Mixins in the `org` folder of the Replay mod (as in issue #2), requiring you to delete the `org` folder. I find that this does not happen anymore in GNTH 2.5.1 running on either Java 8 or Java 21. The game and mod still seem to run fine without it either, though.

**Comment by wohaopa** [comment]
The previous need to delete org was because unimixin could not be forced to load and compatible with version 0.7 at that time. But now, unimixin has done it.
